version: "3"

services:
    minio:
        container_name: minio
        build:
            context: ./minio
            dockerfile: Dockerfile
        environment:
            MINIO_ROOT_USER: localid #AWS Access Key ID
            MINIO_ROOT_PASSWORD: localpassword #AWS Secret Access Key
        entrypoint: bash
        command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
        volumes:
            - ./minio/data:/export  # MinIOストレージの永続化
        ports:
            - '9000:9999'
            - '9001:9001'
    centos7:
        container_name: centos7
        build:
            context: ./centos-centos7
            dockerfile: Dockerfile
        ports:
            - '80:80'
            - '443:443'
    mysql57:
        container_name: mysql57
        build:
            context: ./mysql57
            dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: root #AWS Access Key ID
            MYSQL_USER: local #AWS Secret Access Key
            MYSQL_PASSWORD: localpassword #AWS Secret Access Key
        volumes:
            - mysql57-data:/var/lib/mysql # mysqlストレージの永続化
        ports:
            - '3306:3306'
volumes:
    mysql57-data:
