version: "3"

services:
    minio:
        container_name: minio
        build:
            context: ./minio
            dockerfile: Dockerfile
        environment:
            MINIO_ROOT_USER: localid #AWS Access Key ID
            MINIO_ROOT_PASSWORD: localpassword #AWS Secret Access Key
        entrypoint: bash
        command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
        volumes:
            - ./minio/data:/export  # MinIOストレージの永続化
        ports:
            - '9000:9999'
            - '9001:9001'
    centos7-php73:
        container_name: centos7-php73
        build:
            context: centos7-php73
            dockerfile: Dockerfile
        ports:
            - '80:80'
            - '443:443'
    mysql57:
        container_name: mysql57
        build:
            context: ./mysql57
            dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: local
            MYSQL_PASSWORD: localpassword
        volumes:
            - mysql57-data:/var/lib/mysql # mysqlストレージの永続化
        ports:
            - '3306:3306'
    alpine-vsftpd:
        container_name: alpine-vsftpd
        hostname: alpine-vsftpd # use pasv_address and configure pasv_addr_resolve=YES
        build:
            context: alpine-vsftpd
            dockerfile: Dockerfile
        volumes:
            - ./alpine-vsftpd/log:/var/log
        ports:
            - '20-22:20-22'
            - "10090-10100:10090-10100"

volumes:
    mysql57-data:
